# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9ddb06a9f9c04634ce2864074871be26fb90cc60d0b77dfc0f877081ec14ca7f40d73ea9cc526a9b94c6c20a4f2b05ddc0f3561559ed20c579ce60b5117c33d

test:
  secret_key_base: bdf044510be7e70ebdd575ec22a2ac4cf898dcbe57a96e9038614707dcc32571f5394acf992c2b8063cae7aaf50354af165092bb1964d1a6c6c9ada2d384da41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
